"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { useEffect } from "react";
import { usePathname } from "next/navigation";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  useEffect(() => {
    const pageTitles = {
      "/": "Inicio | SuMuebles",
      "/cocinas": "Cocinas | SuMuebles",
      "/placares": "Placares | SuMuebles",
      "/especiales": "Especiales | SuMuebles",
      "/contacto": "Contacto | SuMuebles",
    };

    document.title = pageTitles[pathname] || "Mi Sitio Web";
  }, [pathname]);
  const [isOpen, setIsOpen] = useState(false);

  const toggleNav = () => {
    setIsOpen(!isOpen);
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex flex-row flex-wrap justify-between sm:justify-between px-4 items-center sticky top-0 bg-black z-10">
        <Link className="logo min-w-12 min-h-12" href="/">
        <Image
          className="object-cover hover:opacity-50 ease-linear duration-150"
          src="/logo.png"
          alt="Sumuebles logo"
          width={50}
          height={50}
          priority
        />
      </Link>

      {/* menu desktop */}
      <div className="hidden sm:flex">
        <ul className="flex flex-row justify-end gap-10">
          <li><Link href="/cocinas" className="hover:underline hover:underline-offset-4 decoration-[#c44309]">Cocinas</Link></li>
          <li><Link href="/placares" className="hover:underline hover:underline-offset-4 decoration-[#c44309]">Placares</Link></li>
          <li><Link href="/especiales" className="hover:underline hover:underline-offset-4 decoration-[#c44309]">Especiales</Link></li>
          <li><Link href="/contacto" className="hover:underline hover:underline-offset-4 decoration-[#c44309]">Contacto</Link></li>
        </ul>
      </div>

      {/* menu mobile */}
      <div className="sm:hidden">
        <button onClick={toggleNav}>
          <Image
            className="invert"
            src="/nav-icon.svg"
            alt="nav icon"
            width={20}
            height={20}
          />
        </button>
      </div>

      {/* desplegable mobile*/}
      {isOpen && (
        <div className="absolute top-12 left-0 w-full bg-black text-white sm:hidden">
          <ul className="flex flex-col items-end gap-4 p-4">
            <li><Link href="/cocinas" onClick={toggleNav}>Cocinas</Link></li>
            <li><Link href="/placares" onClick={toggleNav}>Placares</Link></li>
            <li><Link href="/especiales" onClick={toggleNav}>Especiales</Link></li>
            <li><Link href="/contacto" onClick={toggleNav}>Contacto</Link></li>
            <li><a href="https://www.sumueblesshop.com/" onClick={toggleNav} className="text-orange-700 font-bold">¡Tienda virtual!</a></li>
          </ul>
        </div>
      )}
        </nav>
        {children}
        <div className="flex gap-4 items-center flex-col sm:flex-row justify-center">
          <a
            className="rounded-full border border-solid border-transparent transition-colors flex items-center justify-center bg-[#c44309] text-background gap-2 hover:bg-[#383838] dark:hover:bg-[#ccc] text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5"
            href="https://wa.me/5491170620655?text=Hola!%20Te%20contacto%20desde%20SuMuebles.com"
            target="_blank"
            rel="noopener noreferrer"
          >
          <Image
            src="/whatsapp-brands.svg"
            alt="whatsapp logo"
            width={20}
            height={20}
          />
            WhatsApp
          </a>
          <Link
            className="rounded-full border border-solid border-black/[.08] dark:border-white/[.145] transition-colors flex items-center justify-center hover:bg-[#f2f2f2] dark:hover:bg-[#1a1a1a] hover:border-transparent text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 sm:min-w-44"
            href="/contacto"
            target="_blank"
            rel="noopener noreferrer"
          >
            Contacto
          </Link>
        </div>
        <footer className="row-start-3 flex gap-14 flex-wrap items-center justify-center p-12">
          <a
            className="flex items-center gap-2 hover:underline hover:underline-offset-4"
            href="https://www.instagram.com/sumuebles_/"
            target="_blank"
            rel="noopener noreferrer"
          >
          <Image
            className="invert"
            aria-hidden
            src="/instagram-brands.svg"
            alt="intagram icon"
            width={16}
            height={16}
           />
            Instagram
          </a>
          <a
            className="flex items-center gap-2 hover:underline hover:underline-offset-4"
            href="https://www.facebook.com/sumueblesargentina"
            target="_blank"
            rel="noopener noreferrer"
          >
          <Image
            className="invert"
            aria-hidden
            src="/facebook-f-brands.svg"
            alt="facebook icon"
            width={10}
            height={10}
          />
            Facebook
          </a>
          <a
            className="flex items-center gap-2 hover:underline hover:underline-offset-4"
            href="mailto:sumueblesshop@hotmail.com"
            target="_blank"
            rel="noopener noreferrer"
          >
          <Image
            className="invert"
            aria-hidden
            src="/envelope-solid.svg"
            alt="envelope icon"
            width={16}
            height={16}
          />
            Email
          </a>
          </footer>
          <div className="z-20 hidden sm:block hover:opacity-60">
            <a href="https://www.sumueblesshop.com/" className="fixed top-[85%] left-[75%] xl:left-[80%] 2xl:left-[85%] flex flex-col items-center">
              <Image
                src="/logo.png"
                alt="logo"
                width={40}
                height={40}
              />
          ¡Visita nuestra tienda virtual!
          </a>
          </div>
          <div className="text-center">
            <h6 className="text-xs">Copyright © 2025 SuMuebles®</h6>
          </div>
      </body>
    </html>
  );
}
